//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfOverWinServiceTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.INdeService")]
    public interface INdeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetLastTrainEvents", ReplyAction="http://tempuri.org/INdeService/GetLastTrainEventsResponse")]
        NdeDataClasses.TrainEvent[] GetLastTrainEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetLastTrainEvents", ReplyAction="http://tempuri.org/INdeService/GetLastTrainEventsResponse")]
        System.Threading.Tasks.Task<NdeDataClasses.TrainEvent[]> GetLastTrainEventsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetWorkVectors", ReplyAction="http://tempuri.org/INdeService/GetWorkVectorsResponse")]
        NdeDataClasses.TrainWorking[] GetWorkVectors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetWorkVectors", ReplyAction="http://tempuri.org/INdeService/GetWorkVectorsResponse")]
        System.Threading.Tasks.Task<NdeDataClasses.TrainWorking[]> GetWorkVectorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetWorkMessages", ReplyAction="http://tempuri.org/INdeService/GetWorkMessagesResponse")]
        NdeDataClasses.WorkMessage[] GetWorkMessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetWorkMessages", ReplyAction="http://tempuri.org/INdeService/GetWorkMessagesResponse")]
        System.Threading.Tasks.Task<NdeDataClasses.WorkMessage[]> GetWorkMessagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetGIDMessages", ReplyAction="http://tempuri.org/INdeService/GetGIDMessagesResponse")]
        NdeDataClasses.GIDMessage[] GetGIDMessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetGIDMessages", ReplyAction="http://tempuri.org/INdeService/GetGIDMessagesResponse")]
        System.Threading.Tasks.Task<NdeDataClasses.GIDMessage[]> GetGIDMessagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetComDefinitions", ReplyAction="http://tempuri.org/INdeService/GetComDefinitionsResponse")]
        NdeDataClasses.ComDefinition[] GetComDefinitions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetComDefinitions", ReplyAction="http://tempuri.org/INdeService/GetComDefinitionsResponse")]
        System.Threading.Tasks.Task<NdeDataClasses.ComDefinition[]> GetComDefinitionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetComDefinitionsNoRun", ReplyAction="http://tempuri.org/INdeService/GetComDefinitionsNoRunResponse")]
        NdeDataClasses.ComDefinition[] GetComDefinitionsNoRun();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetComDefinitionsNoRun", ReplyAction="http://tempuri.org/INdeService/GetComDefinitionsNoRunResponse")]
        System.Threading.Tasks.Task<NdeDataClasses.ComDefinition[]> GetComDefinitionsNoRunAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetRequests", ReplyAction="http://tempuri.org/INdeService/GetRequestsResponse")]
        string[] GetRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetRequests", ReplyAction="http://tempuri.org/INdeService/GetRequestsResponse")]
        System.Threading.Tasks.Task<string[]> GetRequestsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/ExecuteBindingCommand", ReplyAction="http://tempuri.org/INdeService/ExecuteBindingCommandResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.BindTrainThreadsCommnand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.AssignTrainNumberCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.AssignMessForTrainCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.StopMessForTrainCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.RunTrackIoTrackCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.TrainProcessCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.SetTrackInCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.MarkTrainCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.MarkMessageCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.WriteTrainInputCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.WriteTrainOutputCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.TrackPointMessagesCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.BindPlanToTrainCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.DelPlanWireCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.SetDefSendFlagCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.SetReplysCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.Buh2DataCommand))]
        string ExecuteBindingCommand(NdeDataClasses.Commands.BindingCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/ExecuteBindingCommand", ReplyAction="http://tempuri.org/INdeService/ExecuteBindingCommandResponse")]
        System.Threading.Tasks.Task<string> ExecuteBindingCommandAsync(NdeDataClasses.Commands.BindingCommand command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INdeServiceChannel : WcfOverWinServiceTest.ServiceReference1.INdeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NdeServiceClient : System.ServiceModel.ClientBase<WcfOverWinServiceTest.ServiceReference1.INdeService>, WcfOverWinServiceTest.ServiceReference1.INdeService {
        
        public NdeServiceClient() {
        }
        
        public NdeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NdeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NdeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NdeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NdeDataClasses.TrainEvent[] GetLastTrainEvents() {
            return base.Channel.GetLastTrainEvents();
        }
        
        public System.Threading.Tasks.Task<NdeDataClasses.TrainEvent[]> GetLastTrainEventsAsync() {
            return base.Channel.GetLastTrainEventsAsync();
        }
        
        public NdeDataClasses.TrainWorking[] GetWorkVectors() {
            return base.Channel.GetWorkVectors();
        }
        
        public System.Threading.Tasks.Task<NdeDataClasses.TrainWorking[]> GetWorkVectorsAsync() {
            return base.Channel.GetWorkVectorsAsync();
        }
        
        public NdeDataClasses.WorkMessage[] GetWorkMessages() {
            return base.Channel.GetWorkMessages();
        }
        
        public System.Threading.Tasks.Task<NdeDataClasses.WorkMessage[]> GetWorkMessagesAsync() {
            return base.Channel.GetWorkMessagesAsync();
        }
        
        public NdeDataClasses.GIDMessage[] GetGIDMessages() {
            return base.Channel.GetGIDMessages();
        }
        
        public System.Threading.Tasks.Task<NdeDataClasses.GIDMessage[]> GetGIDMessagesAsync() {
            return base.Channel.GetGIDMessagesAsync();
        }
        
        public NdeDataClasses.ComDefinition[] GetComDefinitions() {
            return base.Channel.GetComDefinitions();
        }
        
        public System.Threading.Tasks.Task<NdeDataClasses.ComDefinition[]> GetComDefinitionsAsync() {
            return base.Channel.GetComDefinitionsAsync();
        }
        
        public NdeDataClasses.ComDefinition[] GetComDefinitionsNoRun() {
            return base.Channel.GetComDefinitionsNoRun();
        }
        
        public System.Threading.Tasks.Task<NdeDataClasses.ComDefinition[]> GetComDefinitionsNoRunAsync() {
            return base.Channel.GetComDefinitionsNoRunAsync();
        }
        
        public string[] GetRequests() {
            return base.Channel.GetRequests();
        }
        
        public System.Threading.Tasks.Task<string[]> GetRequestsAsync() {
            return base.Channel.GetRequestsAsync();
        }
        
        public string ExecuteBindingCommand(NdeDataClasses.Commands.BindingCommand command) {
            return base.Channel.ExecuteBindingCommand(command);
        }
        
        public System.Threading.Tasks.Task<string> ExecuteBindingCommandAsync(NdeDataClasses.Commands.BindingCommand command) {
            return base.Channel.ExecuteBindingCommandAsync(command);
        }
    }
}
