//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceNdeTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.INdeService")]
    public interface INdeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetLastTrainEvents", ReplyAction="http://tempuri.org/INdeService/GetLastTrainEventsResponse")]
        NdeDataClasses.TrainEvent[] GetLastTrainEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetWorkVectors", ReplyAction="http://tempuri.org/INdeService/GetWorkVectorsResponse")]
        NdeDataClasses.TrainWorking[] GetWorkVectors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetWorkMessages", ReplyAction="http://tempuri.org/INdeService/GetWorkMessagesResponse")]
        NdeDataClasses.WorkMessage[] GetWorkMessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetGIDMessages", ReplyAction="http://tempuri.org/INdeService/GetGIDMessagesResponse")]
        NdeDataClasses.GIDMessage[] GetGIDMessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetComDefinitions", ReplyAction="http://tempuri.org/INdeService/GetComDefinitionsResponse")]
        NdeDataClasses.ComDefinition[] GetComDefinitions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/ExecuteBindingCommand", ReplyAction="http://tempuri.org/INdeService/ExecuteBindingCommandResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.AssignTrainNumberCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.SetTrackInCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.AssignMessForTrainCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.RunTrackIoTrackCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.TrainProcessCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.MarkMessageCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.WriteTrainInputCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.StopMessForTrainCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.MarkTrainCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.WriteTrainOutputCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.DelPlanWireCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.BindTrainThreadsCommnand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.TrackPointMessagesCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NdeDataClasses.Commands.BindPlanToTrainCommand))]
        string ExecuteBindingCommand(NdeDataClasses.Commands.BindingCommand command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INdeServiceChannel : ServiceNdeTest.ServiceReference1.INdeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NdeServiceClient : System.ServiceModel.ClientBase<ServiceNdeTest.ServiceReference1.INdeService>, ServiceNdeTest.ServiceReference1.INdeService {
        
        public NdeServiceClient() {
        }
        
        public NdeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NdeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NdeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NdeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NdeDataClasses.TrainEvent[] GetLastTrainEvents() {
            return base.Channel.GetLastTrainEvents();
        }
        
        public NdeDataClasses.TrainWorking[] GetWorkVectors() {
            return base.Channel.GetWorkVectors();
        }
        
        public NdeDataClasses.WorkMessage[] GetWorkMessages() {
            return base.Channel.GetWorkMessages();
        }
        
        public NdeDataClasses.GIDMessage[] GetGIDMessages() {
            return base.Channel.GetGIDMessages();
        }
        
        public NdeDataClasses.ComDefinition[] GetComDefinitions() {
            return base.Channel.GetComDefinitions();
        }
        
        public string ExecuteBindingCommand(NdeDataClasses.Commands.BindingCommand command) {
            return base.Channel.ExecuteBindingCommand(command);
        }
    }
}
